#!/bin/bash

cat input | awk '  
output = "out.json"
BEGIN { 
	FS="=" 
	print "[" > "out.json"
}

NR == 1 { 
	ELEMENT=$2
	FS=","         
}

NR == 2 { 
	for(i=1; i<=NF; i++) 
    {
		tag_name[i]=$i
	}
}

/^$/ { 
	next
}


NR > 2 {
		if ( NR != 3 )
			print "," >> output

		print  "\t\""ELEMENT"\"" ":"" " "{" >> output


		for (j=1; j<=NF; j++)
		{
			tag_content = $j

			printf "\t\t" "\"" tag_name[j]"\"" "  " ":""  ""\""tag_content"\""  >> output

			if(j != NF)
				printf "," >> output  

			print "" >> output 
			
        }


		printf "\t}" >> output 
}
    
END {
	print "\n]" >> output
}
 
'
